general {
    lock_cmd = pidof hyprlock || hyprlock --config $HOME/.config/hypr/arch-pl-lock.conf
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}
listener { timeout = 300; on-timeout = $HOME/.local/share/arch-pl-os/bin/wygaszacz; on-resume = pkill -f '/arch-pl-os/wygaszacz.py' || true }
listener { timeout = 600; on-timeout = loginctl lock-session }
listener { timeout = 900; on-timeout = hyprctl dispatch dpms off; on-resume = hyprctl dispatch dpms on }
